### ISSUE TITLE
남산운수의 버스 차종 교체로 인한 버스 사이즈 구분 문제

### ISSUE THREAD

**Issue by gwongibeom** [resten1497/yongsan03bus_bot#2]
# 이슈 내용
남산운수가 버스의 차종을 바꾸면서 용산 03 챗봇에서 작은버스가 큰버스로 뜨고 큰버스가 작은 버스로 보이는 이슈가 발생하였음.

**Comment by gwongibeom** [comment]
용산03의 버스 차종이 바뀌면서 버스ID가 각각 뒤섞이게 되어 작은버스를 큰버스로 인식하고 큰버스를 작은 버스로 인식하게 됨.

<img src="https://blog.kakaocdn.net/dn/dAW0hv/btsGMfHJJnX/krOmiTHDFTVK0kdQS6gMqK/img.png">

코드를 살펴본 결과 버스 사이즈를 리턴하는 함수에서 인자로 vehId를 받아온 뒤 하드코딩되어 있는 작은버스와 큰버스의 배열을 대조하여 반환하는 방식이여서 발생한 문제로 확인 됨

**Comment by gwongibeom** [comment]
@resten1497 혹시 이 이슈 제가 한번 해결해봐도 될까요? 제가 오픈소스 기여는 번역기여만 해보고 코드적인 부분은 기여해보지 않아서 하드코딩적인 부분이지만 한번 코드 기여를 해보고 싶습니다!

용산03봇 정말 감사히 잘 쓰고 있습니다!

-- 스스 9기 권기범 --

**Comment by resten1497** [comment]
안녕하세요 
개발자 정상현입니다. 

우선 03봇을 잘 사용해주시는것에 너무 감사드립니다.
버스 정보 이슈가 있는거로 확인이 되었는데, 제가 파악했을때 차량번호가 5717~ 5720 으로 끝나는 것으로 알고 있습니다.

혹시 번호는 그대로인데 차량 자체가 바뀐것일까요?

**Comment by gwongibeom** [comment]
네 지금 상황을 보면 그런 것 같습니다. 눈으로 직접 확인하진 않았는데 네이버맵 기준으로 조회해보면 차량번호는 유지되어 있는것 같습니다. 아직 정확히 확인 된 것은 아니지만 추측을 해보자면 구형 큰버스가 신형 작은 버스로 바뀐 케이스도 있고 작은 구형이 작은 신형 버스로 변경 된 케이스도 있는 것 같습니다.

**Comment by resten1497** [comment]
일단 코드를 적용하기 이전에 한번 다시 체크해볼 필요가 있을것같습니다.
문제되는 케이스들을 육안으로 조사해서 알려주실 수 있으실까요?
저도 일단 다시 확인해보겠습니다

Ex: 5719 : 차량변경으로 큰버스 -> 작은버스

**Comment by gwongibeom** [comment]
육안으로는 정말 아쉽게도 시간상 조금 힘들 것 같고 차량번호 조회로 확인은 가능 할 것 같습니다.

**Comment by gwongibeom** [comment]
번호 | 차종(연식) | is소형
-- | -- | --
서울75사5716 | 뉴-카운티(2024) | Y
서울75사5717 | 현대그린시티(2022) | N
서울75사5718 | 뉴-카운티(2020) | Y
서울75사5719 | 뉴-카운티(2024) | Y
서울75사5720 | 뉴-카운티(2024) | Y


차량번호 조회 결과입니다. 큰 버스 하나가 작은버스로 바뀐 것 같습니다!

**Comment by resten1497** [comment]
네 확인했습니다 
github랑 서버랑 자동 Push 연동이 안되어있어서, PR 올려주시면 바로 반영하도록 하겠습니다.

혹시 해당 자료를 어디서 확인하셨는지 알 수 있을까요?
제 기억상 5721도 있었던 것같아서요

**Comment by gwongibeom** [comment]
엇 그렇네요!

번호 | 차종(연식) | is소형
-- | -- | --
서울75사5716 | 뉴-카운티(2024) | Y
서울75사5717 | 현대그린시티(2022) | N
서울75사5718 | 뉴-카운티(2020) | Y
서울75사5719 | 뉴-카운티(2024) | Y
서울75사5720 | 뉴-카운티(2024) | Y
서울75사5721 | 뉴-카운티(2024) | Y

21번까지 조회한 리스트입니다.

조회는 차량번호 조회 할 수 있는 자동차365 서비스가 유료라서 무료로 조회 가능한 헤이딜러 앱에서 직접 일일히 조회하였습니다.

**Comment by resten1497** [comment]
고생하셨습니다.

PR올려주시면 반영하겠습니다

**Comment by gwongibeom** [comment]
```js 
const BigSize = ["102025099", "102025102"];
```

혹시 두 개의 큰버스 vehId 중 어느게 서울75사5717인지 혹시 기억 하시나요?

**Comment by resten1497** [comment]
id를 개별적으로 수집한거라 조금 시간이 걸릴것같은데 찾는대로 바로 알려드릴께요!

**Comment by gwongibeom** [comment]
![화면 캡처 2024-04-19 112131](https://github.com/resten1497/yongsan03bus_bot/assets/47078599/4c5c9aa8-5732-49bd-b97a-f0fb0a8594a1)

![KakaoTalk_20240419_112223135](https://github.com/resten1497/yongsan03bus_bot/assets/47078599/103932cc-f719-41ae-8dc6-1df5ade841d0)


id찾았습니다! ```102025102``` 같아요!



번호 | 차종(연식) | is소형 | 작은 버스로 인식하는가
-- | -- | -- | --
서울75사5716 | 뉴-카운티(2024) | Y | Y
서울75사5717 | 현대그린시티(2022) | N | N
서울75사5718 | 뉴-카운티(2020) | Y | Y
서울75사5719 | 뉴-카운티(2024) | Y | Y
서울75사5720 | 뉴-카운티(2024) | Y | N
서울75사5721 | 뉴-카운티(2024) | Y | Y

**Comment by gwongibeom** [comment]
https://github.com/resten1497/yongsan03bus_bot/pull/3

보시고 Merge 부탁드려요!

**Comment by gwongibeom** [comment]
이슈 해결
